# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-06 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='disliked',
            field=models.ManyToManyField(blank=True, related_name='comment_disliked_by', to='forum.AppUser'),
        ),
        migrations.AddField(
            model_name='comment',
            name='liked',
            field=models.ManyToManyField(blank=True, related_name='comment_liked_by', to='forum.AppUser'),
        ),
        migrations.AddField(
            model_name='post',
            name='disliked',
            field=models.ManyToManyField(blank=True, related_name='post_disliked_by', to='forum.AppUser'),
        ),
        migrations.AddField(
            model_name='post',
            name='liked',
            field=models.ManyToManyField(blank=True, related_name='post_liked_by', to='forum.AppUser'),
        ),
    ]
